name: win release
on: workflow_dispatch

jobs:
  build:
    name: flutter release
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v3
        - id: read-version
          uses: NiklasLehnfeld/flutter-version-number-action@main
          with:
            file-path: pubspec.yaml
        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
            flutter-version: '3.27.1'
        - name: Install project dependencies
          run: flutter pub get
        - name: Enable windows build
          run: flutter config --enable-windows-desktop
        - name: Build artifacts
          run: flutter build windows --release
        - name: Archive Release
          uses: thedoctor0/zip-release@master
          with:
            type: 'zip'
            filename: wartsila_manual_explorer-${{github.ref_name}}-windows-${{steps.read-version.outputs.version-number}}.zip
            directory: build/windows/x64/runner/Release
        - name: Release
          uses: softprops/action-gh-release@v1
          with:
            tag_name: wartsila_manual_explorer-win-${{steps.read-version.outputs.version-number}}
            files: build/windows/x64/runner/Release/wartsila_manual_explorer-${{github.ref_name}}-windows-${{steps.read-version.outputs.version-number}}.zip
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
